# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TractGeolocationFormatter
                                 A QGIS plugin
 This plugin transforms user geolocation data into TRACT's geolocation template format
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-03
        git sha              : $Format:%H$
        author               : GeolocWidget
        email                : luiscartor@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import re

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QVariant, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import (
    QAction,
    QMessageBox,
    QFileDialog,
    QDialog,
    QVBoxLayout,
    QLabel,
    QPlainTextEdit,
    QDialogButtonBox,
    QProgressBar,
    QApplication
)

from qgis.core import (
    QgsProject,
    QgsMapLayer,
    QgsGeometry,
    QgsWkbTypes,
    QgsVectorFileWriter,
    QgsFeature,
    QgsField,
    QgsFields,
    QgsGeometry,
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    Qgis
)

from .resources_rc import *
from .TRACT_Geolocation_Formatter_dialog import TractGeolocationFormatterDialog

# Constants for Minimum Area Checks
MIN_PLOT_AREA_HA = 0.05
AREA_CRS = QgsCoordinateReferenceSystem("EPSG:6933")  # Equal-area CRS
COORD_DECIMALS = 6


class TractGeolocationFormatter:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'TractGeolocationFormatter_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&TRACT Geolocation Formatter')

        # Check if plugin was started the first time in current QGIS session
        self.first_start = True

        self.dlg = None
        self._polygon_layers = []

    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        return QCoreApplication.translate('TractGeolocationFormatter', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        icon_path = ':/plugins/tract_geolocation_formatter/icon.png'
        self.add_action(
            icon_path,
            text=self.tr('TRACT Geolocation Formatter'),
            callback=self.run,
            parent=self.iface.mainWindow(),
        )

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(self.tr('&TRACT Geolocation Formatter'), action)
            self.iface.removeToolBarIcon(action)

    # ---------------------------------------------------------------------
    # Main entry point
    # ---------------------------------------------------------------------
    def run(self):
        """Show dialog and run transformation if user presses OK."""
        if self.first_start:
            self.first_start = False
            self.dlg = TractGeolocationFormatterDialog()
            # Connect browse button once
            self.dlg.outputBrowseButton.clicked.connect(self._browse_output_path)

        # Populate dialog every time (layers, fields, defaults)
        self._populate_dialog()

        result = self.dlg.exec_()
        if not result:
            return

        self._run_transformation_from_dialog()

    # ---------------------------------------------------------------------
    # Dialog population helpers
    # ---------------------------------------------------------------------
    def _log(self, msg):
        # """Append a line to the dialog log box."""
        # if self.dlg and hasattr(self.dlg, "logTextEdit"):
        #     self.dlg.logTextEdit.appendPlainText(msg)
        return # Tool description panel is no longer used for logging, so disabled for now

    def _polygon_vector_layers(self):
        """Return list of polygon/multipolygon QgsVectorLayers in the project."""
        layers = []
        for layer in QgsProject.instance().mapLayers().values():
            if layer.type() != QgsMapLayer.VectorLayer:
                continue
            if layer.geometryType() == QgsWkbTypes.PolygonGeometry:
                layers.append(layer)
        return layers

    def _populate_dialog(self):
        """Fill layer combo, field combos and default options."""
        self.dlg.logTextEdit.appendPlainText("\n--- Running transformation ---\n")

        # Populate layer combo
        self._polygon_layers = self._polygon_vector_layers()
        self.dlg.layerComboBox.clear()
        for layer in self._polygon_layers:
            self.dlg.layerComboBox.addItem(layer.name())

        if not self._polygon_layers:
            self._log(self.tr("No polygon or multipolygon vector layers found in the project."))
        else:
            self._log(self.tr("Found {} polygon/multipolygon layers.").format(len(self._polygon_layers)))

        # Set default NodeID / PlotID options
        self.dlg.nodeExistingRadio.setChecked(True)
        self.dlg.nodeAutoRadio.setChecked(False)

        self.dlg.plotNoneRadio.setChecked(True)
        self.dlg.plotExistingRadio.setChecked(False)
        self.dlg.plotAutoRadio.setChecked(False)

        self.dlg.plotPrefixLineEdit.setText("")

        # Populate field combos based on current layer
        self._populate_field_combos()

        # When user changes layer, refresh field combos
        self.dlg.layerComboBox.currentIndexChanged.connect(self._populate_field_combos)

        # Make some sensible defaults for NodeID / PlotID fields
        self._select_default_fields()

    def _populate_field_combos(self):
        """Populate NodeID and PlotID field comboboxes from selected layer."""
        idx = self.dlg.layerComboBox.currentIndex()
        self.dlg.nodeFieldCombo.clear()
        self.dlg.plotFieldCombo.clear()

        if idx < 0 or idx >= len(self._polygon_layers):
            return

        layer = self._polygon_layers[idx]
        field_names = [f.name() for f in layer.fields()]

        self.dlg.nodeFieldCombo.addItems(field_names)
        self.dlg.plotFieldCombo.addItems(field_names)

    def _select_default_fields(self):
        """Try to preselect sensible NodeID / PlotID fields."""
        idx = self.dlg.layerComboBox.currentIndex()
        if idx < 0 or idx >= len(self._polygon_layers):
            return

        layer = self._polygon_layers[idx]
        field_names = [f.name() for f in layer.fields()]

        def set_combo_default(combo, candidates):
            for i, name in enumerate(field_names):
                if name.lower() in candidates:
                    combo.setCurrentIndex(i)
                    return

        set_combo_default(self.dlg.nodeFieldCombo, ("nodeid", "node_id", "id"))
        set_combo_default(self.dlg.plotFieldCombo, ("plotid", "plot_id", "plot"))

    def _browse_output_path(self):
        """Open a file dialog to choose output GeoJSON path."""
        path, _ = QFileDialog.getSaveFileName(
            self.iface.mainWindow(),
            self.tr("Save TRACT GeoJSON"),
            "",
            self.tr("GeoJSON (*.geojson *.json)"),
        )
        if not path:
            return

        if not path.lower().endswith((".geojson", ".json")):
            path += ".geojson"

        self.dlg.outputPathLineEdit.setText(path)

    # ---------------------------------------------------------------------
    # Geometries helper functions
    # ---------------------------------------------------------------------
    
    def _round_geometry_coordinates(self, geom: QgsGeometry, decimals: int = 6) -> QgsGeometry:
        """
        Round all polygon / multipolygon coordinates to the given number of decimals.
        Returns a new QgsGeometry.
        """
        if geom.isEmpty():
            return geom

        from qgis.core import QgsPointXY, QgsGeometry

        def round_ring(ring):
            rounded = []
            for pt in ring:
                rounded.append(QgsPointXY(round(pt.x(), decimals), round(pt.y(), decimals)))
            return rounded

        # Polygon
        if not geom.isMultipart():
            poly = geom.asPolygon()
            if not poly:
                return geom

            rounded_poly = []
            for ring in poly:
                rounded_poly.append(round_ring(ring))

            return QgsGeometry.fromPolygonXY(rounded_poly)

        # MultiPolygon
        mp = geom.asMultiPolygon()
        if not mp:
            return geom

        rounded_mp = []
        for poly in mp:
            rounded_poly = []
            for ring in poly:
                rounded_poly.append(round_ring(ring))
            rounded_mp.append(rounded_poly)

        return QgsGeometry.fromMultiPolygonXY(rounded_mp)

    def _fix_duplicate_vertices(self, geom: QgsGeometry) -> QgsGeometry:
        """
        Remove consecutive duplicate vertices from a polygon or multipolygon geometry.
        Returns a repaired QgsGeometry.
        """

        if geom.isEmpty():
            return geom

        def clean_ring(coords):
            if not coords:
                return coords

            cleaned = [coords[0]]
            for i in range(1, len(coords)):
                if coords[i] != coords[i - 1]:
                    cleaned.append(coords[i])

            # Ensure closure
            if cleaned[0] != cleaned[-1]:
                cleaned.append(cleaned[0])

            return cleaned

        from qgis.core import QgsPointXY, QgsGeometry

        # ---- Handle simple Polygon ----
        if geom.isMultipart() is False:
            poly = geom.asPolygon()   # [[(x,y), (x,y), ...], [hole], ...]
            if not poly:
                return geom

            new_rings = []
            for ring in poly:
                coords = [(pt.x(), pt.y()) for pt in ring]
                new_coords = clean_ring(coords)
                new_rings.append([QgsPointXY(x, y) for x, y in new_coords])

            return QgsGeometry.fromPolygonXY(new_rings)

        # ---- Handle MultiPolygon ----
        else:
            mp = geom.asMultiPolygon()  # list of polygons → each polygon = list of rings
            if not mp:
                return geom

            new_polygons = []
            for poly in mp:
                new_rings = []
                for ring in poly:
                    coords = [(pt.x(), pt.y()) for pt in ring]
                    new_coords = clean_ring(coords)
                    new_rings.append([QgsPointXY(x, y) for x, y in new_coords])
                new_polygons.append(new_rings)

            return QgsGeometry.fromMultiPolygonXY(new_polygons)


    def _has_z_values(self, geom: QgsGeometry) -> bool:
        """
        Detect real Z-enabled geometries based on WKB type.
        """
        return QgsWkbTypes.hasZ(geom.wkbType())
    
    # Helper to get NodeID and PlotID for a feature
    def _get_ids(self, feature, layer, node_use_existing, node_field_name,
                plot_existing, plot_field_name):
        node_val = ""
        plot_val = ""

        if node_use_existing and node_field_name:
            idx = layer.fields().indexFromName(node_field_name)
            if idx != -1:
                v = feature.attributes()[idx]
                node_val = "" if v is None else str(v)

        if plot_existing and plot_field_name:
            idx = layer.fields().indexFromName(plot_field_name)
            if idx != -1:
                v = feature.attributes()[idx]
                plot_val = "" if v is None else str(v)

        return node_val, plot_val



    # no need for drop_z_values function anymore, as we save with 2D type directly
    # def _drop_z_values(self, geom: QgsGeometry) -> QgsGeometry:
    #     """
    #     Universal, QGIS-version-safe removal of Z values.
    #     Converts geometry to WKT, strips Z notation and 3rd coordinate,
    #     then rebuilds a 2D geometry.
    #     """
    #     if geom.isEmpty():
    #         return geom

    #     wkt = geom.asWkt()

    #     # Remove the ' Z ' dimension tag
    #     wkt = re.sub(r'\bZ\b', '', wkt)

    #     # Remove third coordinates (x y z → x y)
    #     # Handles decimals, negatives, scientific notation
    #     wkt = re.sub(
    #         r'(\d+(\.\d+)?([eE][-+]?\d+)?)[ ]+(\d+(\.\d+)?([eE][-+]?\d+)?)[ ]+(\d+(\.\d+)?([eE][-+]?\d+)?)',
    #         r'\1 \4',
    #         wkt
    #     )

    #     # Build new 2D geometry
    #     new_geom = QgsGeometry.fromWkt(wkt)

    #     if new_geom is None or new_geom.isEmpty():
    #         # fail-safe
    #         return geom

    #     return new_geom





    # ---------------------------------------------------------------------
    # Main transformation logic
    # ---------------------------------------------------------------------

    # Adding a method to show a detailed report dialog with the summary and logs, instead of just a message box
    def _show_report_dialog(self, summary_text):
        """Show a wide, scrollable report dialog."""
        dialog = QDialog(self.iface.mainWindow())
        dialog.setWindowTitle(self.tr("TRACT Geolocation Formatter Report"))
        dialog.resize(1000, 700)
        dialog.setMinimumSize(850, 600)

        layout = QVBoxLayout(dialog)

        intro_label = QLabel(self.tr("Export summary and geometry repair details"))
        intro_label.setWordWrap(True)
        layout.addWidget(intro_label)

        report_text_edit = QPlainTextEdit(dialog)
        report_text_edit.setReadOnly(True)
        report_text_edit.setPlainText(summary_text)
        layout.addWidget(report_text_edit)

        button_box = QDialogButtonBox(QDialogButtonBox.Ok, parent=dialog)
        button_box.accepted.connect(dialog.accept)
        layout.addWidget(button_box)

        dialog.exec_()


    def _run_transformation_from_dialog(self):
        """Read settings from dialog and run the actual transformation."""

        export_blocked = False

        # Track all feature-level geometry fixes in a structured way
        repair_log = {}  # { feature_id : [ "message1", "message2" ] }
        
        # Track validations to reflect in csv report
        validation_rows = []

        # Validate selected layer
        idx = self.dlg.layerComboBox.currentIndex()
        if idx < 0 or idx >= len(self._polygon_layers):
            QMessageBox.warning(
                self.iface.mainWindow(),
                self.tr("TRACT Geolocation Formatter"),
                self.tr("Please select an input polygon layer."),
            )
            return

        layer = self._polygon_layers[idx]

        if layer.geometryType() not in (
            QgsWkbTypes.PolygonGeometry,
        ):
            QMessageBox.warning(
                self.iface.mainWindow(),
                self.tr("TRACT Geolocation Formatter"),
                self.tr("Selected layer is not a polygon or multipolygon layer."),
            )
            return

        field_names = [f.name() for f in layer.fields()]
        if not field_names:
            QMessageBox.warning(
                self.iface.mainWindow(),
                self.tr("TRACT Geolocation Formatter"),
                self.tr("The selected layer has no attributes."),
            )
            return

        # NodeID options
        node_use_existing = self.dlg.nodeExistingRadio.isChecked()
        node_auto = self.dlg.nodeAutoRadio.isChecked()

        # Optional prefix for auto-generated NodeIDs
        node_prefix = ""
        if node_auto:
            node_prefix = self.dlg.nodePrefixLineEdit.text() or ""

        # Must choose one method
        if not node_use_existing and not node_auto:
            QMessageBox.warning(
                self.iface.mainWindow(),
                self.tr("TRACT Geolocation Formatter"),
                self.tr("Please choose how to create NodeID (existing field or auto-generate)."),
            )
            return

        # If using an existing field, validate field selection
        node_field_name = None
        if node_use_existing:
            node_field_name = self.dlg.nodeFieldCombo.currentText()
            if not node_field_name:
                QMessageBox.warning(
                    self.iface.mainWindow(),
                    self.tr("TRACT Geolocation Formatter"),
                    self.tr("Please select a NodeID field."),
                )
                return

        # PlotID options
        plot_none = self.dlg.plotNoneRadio.isChecked()
        plot_existing = self.dlg.plotExistingRadio.isChecked()
        plot_auto = self.dlg.plotAutoRadio.isChecked()

        plot_field_name = None
        plot_prefix = ""

        if plot_existing:
            plot_field_name = self.dlg.plotFieldCombo.currentText()
            if not plot_field_name:
                QMessageBox.warning(
                    self.iface.mainWindow(),
                    self.tr("TRACT Geolocation Formatter"),
                    self.tr("Please select a PlotID field or choose 'No PlotID'."),
                )
                return
        elif plot_auto:
            plot_prefix = self.dlg.plotPrefixLineEdit.text() or ""

        # Output path
        output_path = self.dlg.outputPathLineEdit.text().strip()
        if not output_path:
            QMessageBox.warning(
                self.iface.mainWindow(),
                self.tr("TRACT Geolocation Formatter"),
                self.tr("Please choose an output GeoJSON path."),
            )
            return

        if not output_path.lower().endswith((".geojson", ".json")):
            output_path += ".geojson"
            self.dlg.outputPathLineEdit.setText(output_path)

        # self.dlg.logTextEdit.clear()
        self.dlg.logTextEdit.setPlainText(
            "This tool converts polygon geometries into TRACT's standard geolocation format.\n\n"
            "Automatic fixes applied:\n"
            "- Removal of consecutive duplicate vertices\n"
            "- Geometry validation (makeValid)\n"
            "- Reprojection to EPSG:4326\n\n"
            "Specify NodeID / PlotID and export to a TRACT-ready GeoJSON."
        )


        self._log(self.tr("Starting TRACT GeoJSON export..."))
        self._log(self.tr("Input layer: {}").format(layer.name()))
        self._log(self.tr("Output file: {}").format(output_path))

        # Prepare CRS transform to EPSG:4326
        target_crs = QgsCoordinateReferenceSystem("EPSG:4326")
        transform_context = QgsProject.instance().transformContext()
        coord_transform = None

        # Transformation to calculate areas
        area_transform = QgsCoordinateTransform(
            layer.crs(),
            AREA_CRS,
            transform_context
        )

        if layer.crs() != target_crs:
            coord_transform = QgsCoordinateTransform(layer.crs(), target_crs, transform_context)
            self._log(self.tr("Reprojecting geometries to EPSG:4326..."))
        else:
            self._log(self.tr("Layer already in EPSG:4326."))

        # Output fields
        out_fields = QgsFields()
        out_fields.append(QgsField("NodeID", QVariant.String))
        out_fields.append(QgsField("PlotID", QVariant.String))

        geom_type = layer.wkbType()
        geom_type_2d = QgsWkbTypes.dropZ(geom_type)

        writer = QgsVectorFileWriter(
            output_path,
            "UTF-8",
            out_fields,
            geom_type_2d, # needed to ensure a 2d type
            target_crs,
            "GeoJSON",
        )


        if writer.hasError() != QgsVectorFileWriter.NoError:
            QMessageBox.critical(
                self.iface.mainWindow(),
                self.tr("TRACT Geolocation Formatter"),
                self.tr("Error creating output file: {}").format(writer.errorMessage()),
            )
            del writer
            return

        invalid_features = []
        written_count = 0
        total_count = 0

        small_area_features = []  # list of (fid, area_ha)
        polygon_hole_features = []  # list of fids


        features = list(layer.getFeatures())
        features.sort(key=lambda x: x.id())  # deterministic ordering

        total_features = len(features)

        # Create progress bar in QGIS message bar
        progress_message = self.iface.messageBar().createMessage(
            "TRACT Geolocation Formatter",
            "Processing features..."
        )
        progress = QProgressBar()
        progress.setMaximum(total_features)
        progress.setValue(0)
        progress.setFormat("%v / %m")
        progress.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        progress_message.layout().addWidget(progress)
        progress_item = self.iface.messageBar().pushWidget(progress_message, Qgis.Info)

        try:
            for i, f in enumerate(features, start=1):
                progress.setValue(i)
                QApplication.processEvents()

                total_count += 1
                geom = QgsGeometry(f.geometry())
                if geom.isEmpty():
                    invalid_features.append((f.id(), "Empty geometry"))
                    continue

                if not geom.isGeosValid():
                    fixed = geom.makeValid()
                    if fixed.isEmpty() or not fixed.isGeosValid():
                        invalid_features.append((f.id(), "Invalid geometry (cannot make valid)"))
                        continue
                    geom = fixed

                # --- Z-value removal ---
                if self._has_z_values(geom):
                    if f.id() not in repair_log:
                        repair_log[f.id()] = []
                    repair_log[f.id()].append("Removed Z values")

                    node_id, plot_id = self._get_ids(
                        f,
                        layer,
                        node_use_existing,
                        node_field_name,
                        plot_existing,
                        plot_field_name,
                    )

                    validation_rows.append({
                        "feature_id": f.id(),
                        "NodeID": node_id,
                        "PlotID": plot_id,
                        "status": "WARNING",
                        "issue_type": "z_values",
                        "message": "Removed Z values"
                    })

                # Reproject to EPSG:4326 first
                if coord_transform is not None:
                    try:
                        geom.transform(coord_transform)
                    except Exception as e:
                        invalid_features.append((f.id(), "Reprojection error: {}".format(e)))
                        continue

                # Round coordinates once, after reprojection, before checks
                rounded_geom = self._round_geometry_coordinates(geom, COORD_DECIMALS)

                if rounded_geom.isEmpty():
                    invalid_features.append((f.id(), "Geometry became empty after coordinate rounding"))
                    continue

                if not rounded_geom.equals(geom):
                    if f.id() not in repair_log:
                        repair_log[f.id()] = []
                    repair_log[f.id()].append(f"Rounded coordinates to {COORD_DECIMALS} decimals")

                    node_id, plot_id = self._get_ids(
                        f,
                        layer,
                        node_use_existing,
                        node_field_name,
                        plot_existing,
                        plot_field_name,
                    )

                    validation_rows.append({
                        "feature_id": f.id(),
                        "NodeID": node_id,
                        "PlotID": plot_id,
                        "status": "WARNING",
                        "issue_type": "coordinate_rounding",
                        "message": f"Rounded coordinates to {COORD_DECIMALS} decimals"
                    })

                geom = rounded_geom

                # Duplicate vertex check after rounding, because rounding can create duplicates
                coords = [(v.x(), v.y()) for v in geom.vertices()]
                has_bad_duplicates = False
                for j in range(len(coords) - 1):
                    if coords[j] == coords[j + 1]:
                        has_bad_duplicates = True
                        break

                if has_bad_duplicates:
                    self._log(f"Fixing consecutive duplicate vertices in feature {f.id()}...")

                    if f.id() not in repair_log:
                        repair_log[f.id()] = []

                    repair_log[f.id()].append("Removed consecutive duplicate vertices")

                    node_id, plot_id = self._get_ids(
                        f,
                        layer,
                        node_use_existing,
                        node_field_name,
                        plot_existing,
                        plot_field_name,
                    )

                    validation_rows.append({
                        "feature_id": f.id(),
                        "NodeID": node_id,
                        "PlotID": plot_id,
                        "status": "WARNING",
                        "issue_type": "duplicate_vertices",
                        "message": "Removed consecutive duplicate vertices"
                    })

                    geom = self._fix_duplicate_vertices(geom)

                    if geom.isEmpty() or not geom.isGeosValid():
                        invalid_features.append((f.id(), "Duplicate-vertex fix failed (invalid geometry)"))
                        continue

                # Minimum area check
                try:
                    area_geom = QgsGeometry(geom)
                    area_geom.transform(area_transform)
                    area_m2 = area_geom.area()
                    area_ha = area_m2 / 10000.0
                except Exception as e:
                    invalid_features.append((f.id(), f"Area computation failed: {e}"))
                    continue

                if area_ha < MIN_PLOT_AREA_HA:
                    small_area_features.append((f.id(), area_ha))

                    node_id, plot_id = self._get_ids(
                        f,
                        layer,
                        node_use_existing,
                        node_field_name,
                        plot_existing,
                        plot_field_name,
                    )

                    validation_rows.append({
                        "feature_id": f.id(),
                        "NodeID": node_id,
                        "PlotID": plot_id,
                        "status": "ERROR",
                        "issue_type": "small_area",
                        "message": f"Area below minimum ({area_ha:.4f} ha < {MIN_PLOT_AREA_HA} ha)"
                    })

                    continue

                # Polygon holes detection (report only)
                has_holes = False

                if geom.isMultipart():
                    multipoly = geom.asMultiPolygon()
                    for poly in multipoly:
                        if len(poly) > 1:  # exterior ring + one or more interior rings
                            has_holes = True
                            break
                else:
                    poly = geom.asPolygon()
                    if poly and len(poly) > 1:
                        has_holes = True

                if has_holes:
                    polygon_hole_features.append(f.id())

                    node_id, plot_id = self._get_ids(
                        f,
                        layer,
                        node_use_existing,
                        node_field_name,
                        plot_existing,
                        plot_field_name,
                    )

                    validation_rows.append({
                        "feature_id": f.id(),
                        "NodeID": node_id,
                        "PlotID": plot_id,
                        "status": "ERROR",
                        "issue_type": "polygon_holes",
                        "message": "Polygon contains interior holes"
                    })

                    continue

                new_feat = QgsFeature(out_fields)

                # NodeID
                if node_use_existing:
                    attrs = f.attributes()
                    node_idx = layer.fields().indexFromName(node_field_name)
                    val = attrs[node_idx] if node_idx != -1 else None
                    new_feat["NodeID"] = "" if val is None else str(val)
                else:
                    new_feat["NodeID"] = f"{node_prefix}{written_count + 1}"

                # PlotID
                if plot_none:
                    new_feat["PlotID"] = ""
                elif plot_existing and plot_field_name:
                    attrs = f.attributes()
                    plot_idx = layer.fields().indexFromName(plot_field_name)
                    val = attrs[plot_idx] if plot_idx != -1 else None
                    new_feat["PlotID"] = "" if val is None else str(val)
                elif plot_auto:
                    new_feat["PlotID"] = "{}{}".format(plot_prefix, written_count + 1)
                else:
                    new_feat["PlotID"] = ""

                new_feat.setGeometry(geom)

                if not writer.addFeature(new_feat):
                    invalid_features.append((f.id(), "Failed to write feature to output"))
                    continue

                written_count += 1

        finally:
            self.iface.messageBar().popWidget(progress_item)

        del writer  # flush

        self.iface.messageBar().pushMessage(
            "TRACT Geolocation Formatter",
            f"Finished processing {total_count} features.",
            level=Qgis.Success,
            duration=3
        )

        # # Log small area features
        # if small_area_features:
        #     lines = [
        #         self.tr("Export blocked: polygons below minimum area detected."),
        #         self.tr("Minimum allowed area: {} ha").format(MIN_PLOT_AREA_HA),
        #         self.tr("Number of invalid polygons: {}").format(len(small_area_features)),
        #         "",
        #         self.tr("Examples:")
        #     ]

        #     for fid, area in small_area_features[:10]:
        #         lines.append(f"  FID {fid}: {area:.4f} ha")

        #     if len(small_area_features) > 10:
        #         lines.append(
        #             f"  ... and {len(small_area_features) - 10} more polygons."
        #         )

        #     export_blocked = True

        def _feature_label(fid):
            """
            Helper to build a human-readable feature label, including PlotID if present.
            """
            plot_id = None

            if fid < len(features):
                f = features[fid]
                if plot_existing and plot_field_name:
                    idx = layer.fields().indexFromName(plot_field_name)
                    if idx != -1:
                        val = f.attributes()[idx]
                        if val not in (None, ""):
                            plot_id = str(val)

            if plot_id:
                return f"Feature {fid} (PlotID = {plot_id})"
            else:
                return f"Feature {fid}"


        # Build summary
        summary_lines = [
            self.tr("TRACT GeoJSON export finished."),
            self.tr("Output file: {}").format(output_path),
            self.tr("Total input features: {}").format(total_count),
            self.tr("Successfully written features: {}").format(written_count),
            self.tr("Skipped / invalid features: {}").format(
                len(invalid_features) + len(small_area_features) + len(polygon_hole_features)
            ),
        ]

        summary_lines.append(
            self.tr("Features with geometry repairs applied: {}").format(len(repair_log))
        )

        if repair_log:
            summary_lines.append("")
            summary_lines.append(self.tr("Geometry repair details:"))

            # Limit to 50 features in popup
            max_display = 500
            display_ids = list(repair_log.keys())[:max_display]

            for fid in display_ids:
                messages = repair_log[fid]
                for msg in messages:
                    summary_lines.append(f"  - Feature {fid}: {msg}")

            if len(repair_log) > max_display:
                summary_lines.append(
                    f"  ... and {len(repair_log) - max_display} more features with repairs."
                )

        if invalid_features:
            summary_lines.append("")
            summary_lines.append(self.tr("Examples of skipped features:"))
            for fid, reason in invalid_features[:500]:
                summary_lines.append("  FID {}: {}".format(fid, reason))


        # --- Blocking validation errors (grouped) ---
        if small_area_features or polygon_hole_features:
            summary_lines.append("")
            summary_lines.append(self.tr("Blocking validation errors:"))

            if small_area_features:
                summary_lines.append(
                    self.tr("Polygons below minimum area ({} ha):").format(MIN_PLOT_AREA_HA)
                )
                for fid, area in small_area_features[:500]:
                    summary_lines.append(
                        f"  - {_feature_label(fid)}: {area:.4f} ha"
                    )

                if len(small_area_features) > 500:
                    summary_lines.append(
                        f"  ... and {len(small_area_features) - 500} more polygons."
                    )

            if polygon_hole_features:
                summary_lines.append("")
                summary_lines.append(
                    self.tr("Polygons with interior holes detected:")
                )

                for fid in polygon_hole_features[:500]:
                    summary_lines.append(
                        f"  - {_feature_label(fid)}"
                    )

                if len(polygon_hole_features) > 500:
                    summary_lines.append(
                        f"  ... and {len(polygon_hole_features) - 500} more polygons."
                    )

                summary_lines.append(
                    self.tr("These polygons were not modified by the plugin.")
                )



        summary_text = "\n".join(summary_lines)
        self._log(summary_text)

        # Write validation report CSV if there are any validation rows
        report_path = None
        if validation_rows:
            report_path = os.path.splitext(output_path)[0] + "_validation_report.csv"

            import csv
            with open(report_path, "w", newline="", encoding="utf-8") as f:
                writer = csv.DictWriter(
                    f,
                    fieldnames=[
                        "feature_id",
                        "NodeID",
                        "PlotID",
                        "status",
                        "issue_type",
                        "message",
                    ],
                )
                writer.writeheader()
                for row in validation_rows:
                    writer.writerow(row)

        if report_path:
            summary_lines.append(self.tr("Validation report written to: {}").format(report_path))

        # Rebuilds summary text
        summary_text = "\n".join(summary_lines)
        self._log(summary_text)

        self._show_report_dialog(summary_text)
