# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TractGeolocationFormatter
                                 A QGIS plugin
 This plugin transforms user geolocation data into TRACT's geolocation template format
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-03
        git sha              : $Format:%H$
        author               : GeolocWidget
        email                : luiscartor@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import re
import json
from shapely.geometry import shape, LineString

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import (
    QAction,
    QMessageBox,
    QFileDialog,
    QDialog,
    QVBoxLayout,
    QLabel,
    QPlainTextEdit,
    QDialogButtonBox,
    QProgressBar,
    QApplication
)

from qgis.core import (
    QgsProject,
    QgsMapLayer,
    QgsGeometry,
    QgsWkbTypes,
    QgsVectorFileWriter,
    QgsFeature,
    QgsField,
    QgsFields,
    QgsGeometry,
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    Qgis,
    QgsVectorLayer
)

# Version-safe string field type for QgsField construction.
# QGIS 4 / Qt6 uses QMetaType; QGIS 3.x / Qt5 uses QVariant.
try:
    from qgis.PyQt.QtCore import QMetaType
    STRING_FIELD_TYPE = QMetaType.Type.QString
except (ImportError, AttributeError):
    from qgis.PyQt.QtCore import QVariant as _QVariant
    STRING_FIELD_TYPE = _QVariant.String

from .TRACT_Geolocation_Formatter_dialog import TractGeolocationFormatterDialog

# Constants for Minimum Area Checks
MIN_PLOT_AREA_HA = 0.05
AREA_CRS = QgsCoordinateReferenceSystem("EPSG:6933")  # Equal-area CRS
COORD_DECIMALS = 6

# TRACT output field names — used to detect clashes with input layer fields
TRACT_FIELD_NAMES = {"NodeID", "PlotID", "TRACTStatus", "TRACTIssue"}


# ---------------------------------------------------------------------------
# Self-intersection coordinate helpers (GH-7)
#
# Pure-Shapely helpers; no QGIS imports required at call time. Kept at module
# level so they are unit-testable directly. See:
#   .specify/specs/archive/GH-7-self-intersection-coordinates/plan.md
# ---------------------------------------------------------------------------

def _extract_intersection_points(inter):
    """Flatten a Shapely intersection result to a list of (x, y) tuples.

    Handles Point, MultiPoint and GeometryCollection. Skips LineString /
    MultiLineString (collinear overlap — represents a different topology
    issue, already covered by the duplicate-vertices check).
    """
    if inter.is_empty:
        return []
    gt = inter.geom_type
    if gt == "Point":
        return [(inter.x, inter.y)]
    if gt == "MultiPoint":
        return [(p.x, p.y) for p in inter.geoms]
    if gt == "GeometryCollection":
        out = []
        for g in inter.geoms:
            out.extend(_extract_intersection_points(g))
        return out
    return []


def _dedupe_points(points, tolerance=1e-6):
    """Drop points within Euclidean ``tolerance`` of an already-kept point.

    Preserves iteration order. O(n²) — fine for the small lists we generate
    (typically < 20 raw points even on pathological inputs).
    """
    deduped = []
    for p in points:
        is_dup = False
        for q in deduped:
            dx = p[0] - q[0]
            dy = p[1] - q[1]
            if (dx * dx + dy * dy) ** 0.5 <= tolerance:
                is_dup = True
                break
        if not is_dup:
            deduped.append(p)
    return deduped


def _find_self_intersection_points_in_shape(sg):
    """Find boundary self-intersection points in a Shapely Polygon/MultiPolygon.

    Algorithm: flatten all boundary rings of all polygons (and all components
    of a MultiPolygon) into a single tagged segment list, then do all-pairs
    iteration. Adjacency skipping applies **only within the same ring**:

    - Same-ring pairs with absolute index difference < 2 are skipped (truly
      adjacent in the ring).
    - For closed rings, the ``(0, n-1)`` pair is also skipped (adjacency via
      the ring closure).
    - **Cross-ring** and **cross-component** pairs are *always* checked,
      because that's where touches show up after GEOS ``makeValid()`` has
      repaired a self-intersecting polygon into two components that touch at
      the original crossing point. The pipeline runs ``makeValid()`` before
      this helper (constitution § 2 step 6), so the cross-ring case is the
      common one in practice.

    Collects Point / MultiPoint results; skips collinear-overlap LineString
    results (those represent a different topology issue, already covered by
    the duplicate-vertices check).

    Returns a deduped (within 1e-6 Euclidean distance) list of ``(lon, lat)``
    tuples in iteration order.
    """
    if sg is None or sg.is_empty:
        return []

    # Flatten boundary rings to (ring_id, seg_idx_in_ring, num_segments_in_ring,
    # is_closed, LineString segment). Adjacency is per-ring; ring_id is unique
    # across all rings of all components.
    tagged = []
    ring_id = 0

    def _walk_polygon(poly):
        nonlocal ring_id
        if poly.is_empty:
            return
        boundary = poly.boundary
        if boundary.is_empty:
            return
        rings = list(boundary.geoms) if boundary.geom_type == "MultiLineString" else [boundary]
        for ring in rings:
            coords = list(ring.coords)
            num_segments = len(coords) - 1
            if num_segments < 3:
                ring_id += 1
                continue
            is_closed = coords[0] == coords[-1]
            for seg_idx in range(num_segments):
                seg = LineString([coords[seg_idx], coords[seg_idx + 1]])
                tagged.append((ring_id, seg_idx, num_segments, is_closed, seg))
            ring_id += 1

    if sg.geom_type == "MultiPolygon":
        for poly in sg.geoms:
            _walk_polygon(poly)
    elif sg.geom_type == "Polygon":
        _walk_polygon(sg)
    else:
        return []

    points = []
    n = len(tagged)
    for a in range(n):
        ring_a, idx_a, n_a, closed_a, seg_a = tagged[a]
        for b in range(a + 1, n):
            ring_b, idx_b, _n_b, _closed_b, seg_b = tagged[b]
            if ring_a == ring_b:
                # Same-ring adjacency
                diff = abs(idx_a - idx_b)
                if diff < 2:
                    continue
                if closed_a and diff == n_a - 1:
                    continue
            # Cross-ring or non-adjacent same-ring: check the intersection
            points.extend(_extract_intersection_points(seg_a.intersection(seg_b)))

    return _dedupe_points(points)


def _format_self_intersection_message(points):
    """Build the user-facing self-intersection error string (GH-7 / DEC-6, DEC-7).

    - Empty ``points`` → base string only ("Boundary has self-intersections"),
      preserving DEC-4 backward compatibility.
    - Otherwise: ``base + " at: " + " | ".join(lon,lat …)`` with 6-decimal
      formatting per coordinate. Caps at 5 points; appends
      ``" (and K more)"`` when the input exceeds the cap.
    """
    base = "Boundary has self-intersections"
    if not points:
        return base
    cap = 5
    head = points[:cap]
    extra = len(points) - cap
    rendered = " | ".join(f"{lon:.6f},{lat:.6f}" for (lon, lat) in head)
    suffix = f" (and {extra} more)" if extra > 0 else ""
    return f"{base} at: {rendered}{suffix}"


# ---------------------------------------------------------------------------
# Master Data XLSX helpers (GH-6)
#
# Pure-Python helpers for the optional Master Data XLSX writer. Use openpyxl
# (vendored at tract_geolocation_formatter/vendor/openpyxl, bootstrapped via
# __init__.py). Imports are kept lazy inside each function so the plugin's
# module load doesn't break if the vendor dir is missing — the master-data
# feature simply surfaces a clear error at use time.
#
# See:
#   .specify/specs/archive/GH-6-master-data-csv/plan.md (post-archive)
# ---------------------------------------------------------------------------

# Cell mapping per master-data type. Sheet names are extracted verbatim from
# the templates' xl/workbook.xml — note the differing whitespace: the farms
# sheet name has NO space after the period, the farmer-groups sheet name HAS
# a space after the period.
_MASTER_DATA_MAPPING = {
    "farms": {
        "sheet_name": "2.Farms_Template",
        "name_col": "B",
        "country_col": "E",
        "ref_id_col": "I",
    },
    "farmer_groups": {
        "sheet_name": "2. Farmer_Groups Template",
        "name_col": "A",
        "country_col": "C",
        "ref_id_col": "G",
    },
}

# Sentinel placeholder text for the country combo box (DEC-11).
_COUNTRY_COMBO_PLACEHOLDER = "-- select a country --"


def _master_data_output_path(geojson_path, master_data_type):
    """Build the master-data XLSX output path from the GeoJSON output path.

    Strips the .geojson / .json extension and appends
    ``_master_data_{type}.xlsx``. Pure string manipulation.
    """
    base, _ext = os.path.splitext(geojson_path)
    return f"{base}_master_data_{master_data_type}.xlsx"


def _read_country_list_from_template(template_path):
    """Load TRACT's country list from one of the bundled XLSX templates.

    Reads sheet ``"4. Country_List"``, column B, starting row 2; returns the
    list of non-empty country names in TRACT's published order.

    Both bundled templates carry the same country list — either can be passed.
    """
    import openpyxl  # lazy import (DEC-10 — vendored via __init__.py bootstrap)

    wb = openpyxl.load_workbook(template_path, read_only=True, data_only=True)
    try:
        ws = wb["4. Country_List"]
        countries = []
        for row in ws.iter_rows(min_row=2, min_col=2, max_col=2, values_only=True):
            value = row[0]
            if value:
                countries.append(value)
        return countries
    finally:
        wb.close()


def _write_master_data_xlsx(template_path, output_path, master_data_type, country, unique_node_ids):
    """Populate a copy of the bundled template with one row per unique NodeID.

    Loads the template into memory, locates the Template sheet by name,
    writes data rows starting at row 3 into the three columns specified by
    ``_MASTER_DATA_MAPPING[master_data_type]``, then saves to ``output_path``.
    Never modifies the template file on disk.

    Args:
        template_path: filesystem path to the bundled template XLSX.
        output_path: filesystem path to write the populated XLSX to.
        master_data_type: ``"farms"`` or ``"farmer_groups"``.
        country: country name string (full English name from TRACT's list).
        unique_node_ids: ordered list of NodeID strings; duplicates must
            have been removed by the caller — the writer does not dedupe.

    Raises:
        KeyError: if ``master_data_type`` is not in ``_MASTER_DATA_MAPPING``
            or if the expected sheet is missing from the template.
    """
    import openpyxl  # lazy import

    mapping = _MASTER_DATA_MAPPING[master_data_type]
    wb = openpyxl.load_workbook(template_path)
    try:
        ws = wb[mapping["sheet_name"]]
        name_col = mapping["name_col"]
        country_col = mapping["country_col"]
        ref_id_col = mapping["ref_id_col"]

        for offset, node_id in enumerate(unique_node_ids):
            row = 3 + offset
            ws[f"{name_col}{row}"] = node_id
            ws[f"{country_col}{row}"] = country
            ws[f"{ref_id_col}{row}"] = node_id

        wb.save(output_path)
    finally:
        wb.close()


class TractGeolocationFormatter:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'TractGeolocationFormatter_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&TRACT Geolocation Formatter')

        # Check if plugin was started the first time in current QGIS session
        self.first_start = True

        self.dlg = None
        self._polygon_layers = []

    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        return QCoreApplication.translate('TractGeolocationFormatter', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        icon_path = os.path.join(self.plugin_dir, 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr('TRACT Geolocation Formatter'),
            callback=self.run,
            parent=self.iface.mainWindow(),
        )

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(self.tr('&TRACT Geolocation Formatter'), action)
            self.iface.removeToolBarIcon(action)

    # ---------------------------------------------------------------------
    # Main entry point
    # ---------------------------------------------------------------------
    def run(self):
        """Show dialog and run transformation if user presses OK."""
        if self.first_start:
            self.first_start = False
            self.dlg = TractGeolocationFormatterDialog()
            # Connect browse button once
            self.dlg.outputBrowseButton.clicked.connect(self._browse_output_path)
            # Connect NodeID radio buttons
            self.dlg.nodeExistingRadio.toggled.connect(self._update_nodeid_ui_state)
            self.dlg.nodeSameRadio.toggled.connect(self._update_nodeid_ui_state)
            self.dlg.nodeAutoRadio.toggled.connect(self._update_nodeid_ui_state)
            self.dlg.nodeBuildRadio.toggled.connect(self._update_nodeid_ui_state)
            # Connect PlotID radio buttons
            self.dlg.plotNoneRadio.toggled.connect(self._update_plotid_ui_state)
            self.dlg.plotExistingRadio.toggled.connect(self._update_plotid_ui_state)
            self.dlg.plotAutoRadio.toggled.connect(self._update_plotid_ui_state)
            self.dlg.plotBuildRadio.toggled.connect(self._update_plotid_ui_state)
            # Connect Master Data checkbox (GH-6)
            self.dlg.masterDataCheckBox.toggled.connect(self._update_master_data_ui_state)

        # Populate dialog every time (layers, fields, defaults)
        self._populate_dialog()

        result = self.dlg.exec()
        if not result:
            return

        self._run_transformation_from_dialog()

    # ---------------------------------------------------------------------
    # Dialog population helpers
    # ---------------------------------------------------------------------
    def _log(self, msg):
        # """Append a line to the dialog log box."""
        # if self.dlg and hasattr(self.dlg, "logTextEdit"):
        #     self.dlg.logTextEdit.appendPlainText(msg)
        return # Tool description panel is no longer used for logging, so disabled for now

    def _polygon_vector_layers(self):
        """Return list of polygon/multipolygon QgsVectorLayers in the project."""
        layers = []
        for layer in QgsProject.instance().mapLayers().values():
            if layer.type() != QgsMapLayer.VectorLayer:
                continue
            if layer.geometryType() == QgsWkbTypes.PolygonGeometry:
                layers.append(layer)
        return layers

    def _populate_dialog(self):
        """Fill layer combo, field combos and default options."""

        # Populate layer combo
        self._polygon_layers = self._polygon_vector_layers()
        self.dlg.layerComboBox.clear()
        for layer in self._polygon_layers:
            self.dlg.layerComboBox.addItem(layer.name())

        if not self._polygon_layers:
            self._log(self.tr("No polygon or multipolygon vector layers found in the project."))
        else:
            self._log(self.tr("Found {} polygon/multipolygon layers.").format(len(self._polygon_layers)))

        # Set default NodeID / PlotID options
        self.dlg.nodeExistingRadio.setChecked(True)
        self.dlg.nodeSameRadio.setChecked(False)
        self.dlg.nodeAutoRadio.setChecked(False)
        self.dlg.nodeBuildRadio.setChecked(False)

        self.dlg.nodeSameLineEdit.setText("")
        self.dlg.nodeBuildSepLineEdit.setText("_")
        self.dlg.nodeBuildPrefixLineEdit.setText("")
        self.dlg.nodeBuildSuffixLineEdit.setText("")

        self.dlg.plotNoneRadio.setChecked(True)
        self.dlg.plotExistingRadio.setChecked(False)
        self.dlg.plotAutoRadio.setChecked(False)
        self.dlg.plotBuildRadio.setChecked(False)

        self.dlg.plotPrefixLineEdit.setText("")
        self.dlg.plotBuildSepLineEdit.setText("_")
        self.dlg.plotBuildPrefixLineEdit.setText("")
        self.dlg.plotBuildSuffixLineEdit.setText("")

        # Populate field combos based on current layer
        self._populate_field_combos()

        # Apply default field selections
        self._select_default_fields()

        # When user changes layer, refresh combos AND defaults
        try:
            self.dlg.layerComboBox.currentIndexChanged.disconnect()
        except Exception:
            pass

        self.dlg.layerComboBox.currentIndexChanged.connect(self._on_layer_changed)

        # Master Data defaults (GH-6) — checkbox off, Farms preselected, country
        # combo populated with placeholder + 250 entries from TRACT's list.
        self.dlg.masterDataCheckBox.setChecked(False)
        self.dlg.farmsTypeRadio.setChecked(True)
        self._populate_country_combo()
        self.dlg.countryCombo.setCurrentIndex(0)

        # Enable/disable state is refreshed when dialog opens
        self._update_nodeid_ui_state()
        self._update_plotid_ui_state()
        self._update_master_data_ui_state()

    def _update_nodeid_ui_state(self):
        """Enable only the relevant NodeID input widget."""
        self.dlg.nodeFieldCombo.setEnabled(self.dlg.nodeExistingRadio.isChecked())
        self.dlg.nodeSameLineEdit.setEnabled(self.dlg.nodeSameRadio.isChecked())
        self.dlg.nodePrefixLineEdit.setEnabled(self.dlg.nodeAutoRadio.isChecked())
        self.dlg.nodeBuildContainer.setVisible(self.dlg.nodeBuildRadio.isChecked())

    def _update_plotid_ui_state(self):
        """Enable only the relevant PlotID input widget."""
        self.dlg.plotFieldCombo.setEnabled(self.dlg.plotExistingRadio.isChecked())
        self.dlg.plotPrefixLineEdit.setEnabled(self.dlg.plotAutoRadio.isChecked())
        self.dlg.plotBuildContainer.setVisible(self.dlg.plotBuildRadio.isChecked())

    def _update_master_data_ui_state(self):
        """Show/hide master-data sub-controls based on the checkbox state (GH-6)."""
        self.dlg.masterDataContainer.setVisible(self.dlg.masterDataCheckBox.isChecked())

    def _populate_country_combo(self):
        """Populate the country dropdown from the bundled TRACT template (GH-6, DEC-3, DEC-9).

        The country list is cached on first call. Subsequent calls clear and
        re-populate the combo so successive dialog opens are idempotent. On
        failure (e.g. openpyxl missing or template file missing), the combo
        is populated with only the sentinel placeholder — DEC-12's validator
        will block any later attempt to use the master-data feature.
        """
        if not hasattr(self, "_country_list_cache"):
            try:
                template = os.path.join(
                    self.plugin_dir, "templates", "farms_master_data_template.xlsx"
                )
                self._country_list_cache = _read_country_list_from_template(template)
            except Exception as e:
                self._log(f"Failed to load country list from template: {e}")
                self._country_list_cache = []

        self.dlg.countryCombo.clear()
        self.dlg.countryCombo.addItem(_COUNTRY_COMBO_PLACEHOLDER)
        self.dlg.countryCombo.addItems(self._country_list_cache)

    def _populate_field_combos(self):
        """Populate NodeID and PlotID field comboboxes from selected layer."""
        idx = self.dlg.layerComboBox.currentIndex()
        self.dlg.nodeFieldCombo.clear()
        self.dlg.plotFieldCombo.clear()
        self.dlg.nodeBuildField1Combo.clear()
        self.dlg.nodeBuildField2Combo.clear()
        self.dlg.plotBuildField1Combo.clear()
        self.dlg.plotBuildField2Combo.clear()

        if idx < 0 or idx >= len(self._polygon_layers):
            return

        layer = self._polygon_layers[idx]
        field_names = [f.name() for f in layer.fields()]

        self.dlg.nodeFieldCombo.addItems(field_names)
        self.dlg.plotFieldCombo.addItems(field_names)

        # Expression field combos — Field 2 gets an empty first entry (optional)
        self.dlg.nodeBuildField1Combo.addItems(field_names)
        self.dlg.nodeBuildField2Combo.addItem("")
        self.dlg.nodeBuildField2Combo.addItems(field_names)
        self.dlg.plotBuildField1Combo.addItems(field_names)
        self.dlg.plotBuildField2Combo.addItem("")
        self.dlg.plotBuildField2Combo.addItems(field_names)

    def _on_layer_changed(self):
        """Refresh field combos and apply default selections when layer changes."""
        self._populate_field_combos()
        self._select_default_fields()


    def _select_default_fields(self):
        """Try to preselect sensible NodeID / PlotID fields."""
        idx = self.dlg.layerComboBox.currentIndex()
        if idx < 0 or idx >= len(self._polygon_layers):
            return

        layer = self._polygon_layers[idx]
        field_names = [f.name() for f in layer.fields()]
        field_names_lower = [name.lower().strip() for name in field_names]

        def find_field(candidates):
            for candidate in candidates:
                for i, name in enumerate(field_names_lower):
                    if name == candidate:
                        return i
            return -1

        # ---- NodeID ----
        node_idx = find_field(["nodeid", "node_id"])

        if node_idx == -1:
            node_idx = find_field(["id"])  # fallback only

        if node_idx != -1:
            self.dlg.nodeExistingRadio.setChecked(True)
            self.dlg.nodeFieldCombo.setCurrentIndex(node_idx)

        # ---- PlotID ----
        plot_idx = find_field(["plotid", "plot_id", "plot"])

        if plot_idx != -1:
            self.dlg.plotExistingRadio.setChecked(True)
            self.dlg.plotFieldCombo.setCurrentIndex(plot_idx)
        else:
            self.dlg.plotNoneRadio.setChecked(True)

    def _browse_output_path(self):
        """Open a file dialog to choose output GeoJSON path."""
        path, _ = QFileDialog.getSaveFileName(
            self.iface.mainWindow(),
            self.tr("Save TRACT GeoJSON"),
            "",
            self.tr("GeoJSON (*.geojson *.json)"),
        )
        if not path:
            return

        if not path.lower().endswith((".geojson", ".json")):
            path += ".geojson"

        self.dlg.outputPathLineEdit.setText(path)

    # ---------------------------------------------------------------------
    # Geometries helper functions
    # ---------------------------------------------------------------------
    
    def _truncate_geometry_coordinates(self, geom: QgsGeometry, decimals: int = 6) -> QgsGeometry:
        """
        Truncate all polygon / multipolygon coordinates to the given number of decimals
        (no rounding).
        Returns a new QgsGeometry.
        """
        if geom.isEmpty():
            return geom

        from qgis.core import QgsPointXY, QgsGeometry
        import math

        def truncate(value, decimals):
            factor = 10 ** decimals
            return math.trunc(value * factor) / factor

        def truncate_ring(ring):
            truncated = []
            for pt in ring:
                truncated.append(
                    QgsPointXY(
                        truncate(pt.x(), decimals),
                        truncate(pt.y(), decimals)
                    )
                )
            return truncated

        # Polygon
        if not geom.isMultipart():
            poly = geom.asPolygon()
            if not poly:
                return geom

            truncated_poly = []
            for ring in poly:
                truncated_poly.append(truncate_ring(ring))

            return QgsGeometry.fromPolygonXY(truncated_poly)

        # MultiPolygon
        mp = geom.asMultiPolygon()
        if not mp:
            return geom

        truncated_mp = []
        for poly in mp:
            truncated_poly = []
            for ring in poly:
                truncated_poly.append(truncate_ring(ring))
            truncated_mp.append(truncated_poly)

        return QgsGeometry.fromMultiPolygonXY(truncated_mp)

    def _fix_duplicate_vertices(self, geom: QgsGeometry) -> QgsGeometry:
        """
        Remove consecutive duplicate vertices from a polygon or multipolygon geometry.
        Returns a repaired QgsGeometry.
        """

        if geom.isEmpty():
            return geom

        def clean_ring(coords):
            if not coords:
                return coords

            cleaned = [coords[0]]
            for i in range(1, len(coords)):
                if coords[i] != coords[i - 1]:
                    cleaned.append(coords[i])

            # Ensure closure
            if cleaned[0] != cleaned[-1]:
                cleaned.append(cleaned[0])

            return cleaned

        from qgis.core import QgsPointXY, QgsGeometry

        # ---- Handle simple Polygon ----
        if geom.isMultipart() is False:
            poly = geom.asPolygon()   # [[(x,y), (x,y), ...], [hole], ...]
            if not poly:
                return geom

            new_rings = []
            for ring in poly:
                coords = [(pt.x(), pt.y()) for pt in ring]
                new_coords = clean_ring(coords)
                new_rings.append([QgsPointXY(x, y) for x, y in new_coords])

            return QgsGeometry.fromPolygonXY(new_rings)

        # ---- Handle MultiPolygon ----
        else:
            mp = geom.asMultiPolygon()  # list of polygons → each polygon = list of rings
            if not mp:
                return geom

            new_polygons = []
            for poly in mp:
                new_rings = []
                for ring in poly:
                    coords = [(pt.x(), pt.y()) for pt in ring]
                    new_coords = clean_ring(coords)
                    new_rings.append([QgsPointXY(x, y) for x, y in new_coords])
                new_polygons.append(new_rings)

            return QgsGeometry.fromMultiPolygonXY(new_polygons)


    def _has_z_values(self, geom: QgsGeometry) -> bool:
        """
        Detect real Z-enabled geometries based on WKB type.
        """
        return QgsWkbTypes.hasZ(geom.wkbType())
    
    # Helper to get NodeID and PlotID for a feature
    def _get_ids(
        self,
        feature,
        layer,
        node_use_existing,
        node_field_name,
        node_same,
        node_same_value,
        plot_existing,
        plot_field_name
    ):
        node_val = ""
        plot_val = ""

        if node_use_existing and node_field_name:
            idx = layer.fields().indexFromName(node_field_name)
            if idx != -1:
                v = feature.attributes()[idx]
                node_val = "" if v is None else str(v)
        elif node_same:
            node_val = node_same_value

        if plot_existing and plot_field_name:
            idx = layer.fields().indexFromName(plot_field_name)
            if idx != -1:
                v = feature.attributes()[idx]
                plot_val = "" if v is None else str(v)

        return node_val, plot_val

    def _build_expression_value(self, feature, layer, prefix, field1_name, field2_name, suffix, separator):
        """
        Build an ID from expression parts, joining non-empty parts with the separator.

        Parts: prefix, field1 value, field2 value, suffix.
        Empty/null parts are omitted (no double separators).
        """
        parts = []

        if prefix:
            parts.append(prefix)

        if field1_name:
            idx = layer.fields().indexFromName(field1_name)
            if idx != -1:
                val = feature.attributes()[idx]
                if val is not None and str(val) != "":
                    parts.append(str(val))

        if field2_name:
            idx = layer.fields().indexFromName(field2_name)
            if idx != -1:
                val = feature.attributes()[idx]
                if val is not None and str(val) != "":
                    parts.append(str(val))

        if suffix:
            parts.append(suffix)

        return separator.join(parts)

    def _build_output_fields(self, layer_fields, excluded_fields):
        """
        Build the output QgsFields from the input layer fields plus TRACT fields.

        - Fields in `excluded_fields` are skipped (mapped to NodeID/PlotID via "Use existing field").
        - Fields whose name clashes with a TRACT field name get an '_orig' suffix.
        - The four TRACT fields are always appended at the end.

        Returns:
            tuple[QgsFields, dict[str, str]]: (output fields, rename map {original_name: output_name})
        """
        out_fields = QgsFields()
        rename_map = {}

        for field in layer_fields:
            name = field.name()

            if name in excluded_fields:
                continue

            if name in TRACT_FIELD_NAMES:
                new_name = f"{name}_orig"
                rename_map[name] = new_name
                out_fields.append(QgsField(new_name, field.type()))
            else:
                out_fields.append(QgsField(name, field.type()))

        out_fields.append(QgsField("NodeID", STRING_FIELD_TYPE))
        out_fields.append(QgsField("PlotID", STRING_FIELD_TYPE))
        out_fields.append(QgsField("TRACTStatus", STRING_FIELD_TYPE))
        out_fields.append(QgsField("TRACTIssue", STRING_FIELD_TYPE))

        return out_fields, rename_map

    # Helper for after makeValid, to ensure we only keep polygonal parts if we end up with a GeometryCollection
    def _extract_polygonal_geometry(self, geom: QgsGeometry) -> QgsGeometry:
        """
        Ensure the geometry is polygonal.
        If makeValid() returns a GeometryCollection, extract polygon parts only.
        Returns an empty geometry if no polygonal part can be recovered.
        """
        if geom.isEmpty():
            return geom

        wkb_type = geom.wkbType()
        geom_type = QgsWkbTypes.geometryType(wkb_type)

        # Already polygonal
        if geom_type == QgsWkbTypes.PolygonGeometry:
            return geom

        # Try to extract polygon parts from geometry collections
        parts = []
        try:
            for part in geom.constParts():
                part_geom = QgsGeometry(part.clone())
                if QgsWkbTypes.geometryType(part_geom.wkbType()) == QgsWkbTypes.PolygonGeometry:
                    parts.append(part_geom)
        except Exception:
            return QgsGeometry()

        if not parts:
            return QgsGeometry()

        if len(parts) == 1:
            return parts[0]

        # Merge polygon parts into a multipolygon if possible
        collected = []
        for part_geom in parts:
            if part_geom.isMultipart():
                mp = part_geom.asMultiPolygon()
                if mp:
                    collected.extend(mp)
            else:
                poly = part_geom.asPolygon()
                if poly:
                    collected.append(poly)

        if not collected:
            return QgsGeometry()

        return QgsGeometry.fromMultiPolygonXY(collected)


    def _extract_polygon_rings(self, geom: QgsGeometry):
        """
        Helper for TRACT-style geometry checks that need to analyze individual rings.
        Returns polygon rings in normalized form:
        [
            [ring1, ring2, ...],   # polygon 1
            [ring1, ring2, ...],   # polygon 2
        ]
        """
        if geom.isEmpty():
            return []

        if geom.isMultipart():
            mp = geom.asMultiPolygon()
            return mp if mp else []
        else:
            poly = geom.asPolygon()
            return [poly] if poly else []


    def _has_duplicate_vertices_in_rings(self, geom: QgsGeometry) -> bool:
        """
        TRACT-style check:
        duplicate vertices anywhere in a ring, excluding the closing vertex.
        """
        polygon_rings = self._extract_polygon_rings(geom)

        for poly in polygon_rings:
            for ring in poly:
                if len(ring) < 2:
                    continue

                body = ring[:-1]  # exclude closing point
                coords = [(pt.x(), pt.y()) for pt in body]

                if len(set(coords)) < len(coords):
                    return True

        return False


    def _has_rings_with_fewer_than_three_unique_coords(self, geom: QgsGeometry) -> bool:
        """
        TRACT-style check:
        each ring must have at least 3 unique coordinates, excluding closing vertex.
        """
        polygon_rings = self._extract_polygon_rings(geom)

        for poly in polygon_rings:
            for ring in poly:
                if len(ring) < 2:
                    return True

                body = ring[:-1]
                uniq = {(pt.x(), pt.y()) for pt in body}

                if len(uniq) < 3:
                    return True

        return False


    def _has_boundary_self_intersections(self, geom: QgsGeometry) -> bool:
        """
        Exact TRACT-aligned check using Shapely:
        not sg.boundary.is_simple
        """
        if geom is None or geom.isEmpty():
            return False

        try:

            geojson_dict = json.loads(geom.asJson())
            sg = shape(geojson_dict)

            return not sg.boundary.is_simple

        except Exception as e:
            self._log(f"Shapely boundary self-intersection check failed: {e}")
            return False

    def _find_boundary_self_intersection_points(self, geom: QgsGeometry) -> list[tuple[float, float]]:
        """
        Return the deduped (within 1e-6) list of ``(lon, lat)`` boundary
        self-intersection points for ``geom``. Empty list if the boundary is
        simple, the geometry is empty, or any Shapely failure occurs.

        Thin wrapper that converts the QgsGeometry to a Shapely shape and
        delegates to the pure-Python module-level helper
        ``_find_self_intersection_points_in_shape``. See GH-7 / DEC-8.
        """
        if geom is None or geom.isEmpty():
            return []

        try:
            geojson_dict = json.loads(geom.asJson())
            sg = shape(geojson_dict)
            return _find_self_intersection_points_in_shape(sg)
        except Exception as e:
            self._log(f"Shapely self-intersection point finder failed: {e}")
            return []

    def _get_tract_geometry_errors(self, geom: QgsGeometry) -> list[str]:
        """
        Final TRACT-aligned geometry checks. (updated March 2025)
        """
        errors = []

        if geom is None or geom.isEmpty():
            errors.append("Empty geometry")
            return errors

        if QgsWkbTypes.geometryType(geom.wkbType()) != QgsWkbTypes.PolygonGeometry:
            errors.append("Geometry is not polygonal")
            return errors

        if self._has_duplicate_vertices_in_rings(geom):
            errors.append("Duplicated vertices in polygon ring(s)")

        if self._has_rings_with_fewer_than_three_unique_coords(geom):
            errors.append("One or more rings have fewer than three unique coordinates.")

        if self._has_boundary_self_intersections(geom):
            points = self._find_boundary_self_intersection_points(geom)
            errors.append(_format_self_intersection_message(points))

        return errors

    # no need for drop_z_values function anymore, as we save with 2D type directly
    # def _drop_z_values(self, geom: QgsGeometry) -> QgsGeometry:
    #     """
    #     Universal, QGIS-version-safe removal of Z values.
    #     Converts geometry to WKT, strips Z notation and 3rd coordinate,
    #     then rebuilds a 2D geometry.
    #     """
    #     if geom.isEmpty():
    #         return geom

    #     wkt = geom.asWkt()

    #     # Remove the ' Z ' dimension tag
    #     wkt = re.sub(r'\bZ\b', '', wkt)

    #     # Remove third coordinates (x y z → x y)
    #     # Handles decimals, negatives, scientific notation
    #     wkt = re.sub(
    #         r'(\d+(\.\d+)?([eE][-+]?\d+)?)[ ]+(\d+(\.\d+)?([eE][-+]?\d+)?)[ ]+(\d+(\.\d+)?([eE][-+]?\d+)?)',
    #         r'\1 \4',
    #         wkt
    #     )

    #     # Build new 2D geometry
    #     new_geom = QgsGeometry.fromWkt(wkt)

    #     if new_geom is None or new_geom.isEmpty():
    #         # fail-safe
    #         return geom

    #     return new_geom





    # ---------------------------------------------------------------------
    # Main transformation logic
    # ---------------------------------------------------------------------

    # Adding a method to show a detailed report dialog with the summary and logs, instead of just a message box
    def _show_report_dialog(self, summary_text):
        """Show a wide, scrollable report dialog."""
        dialog = QDialog(self.iface.mainWindow())
        dialog.setWindowTitle(self.tr("TRACT Geolocation Formatter Report"))
        dialog.resize(1000, 700)
        dialog.setMinimumSize(850, 600)

        layout = QVBoxLayout(dialog)

        intro_label = QLabel(self.tr("Export summary and geometry repair details"))
        intro_label.setWordWrap(True)
        layout.addWidget(intro_label)

        report_text_edit = QPlainTextEdit(dialog)
        report_text_edit.setReadOnly(True)
        report_text_edit.setPlainText(summary_text)
        layout.addWidget(report_text_edit)

        button_box = QDialogButtonBox(QDialogButtonBox.StandardButton.Ok, parent=dialog)
        button_box.accepted.connect(dialog.accept)
        layout.addWidget(button_box)

        dialog.exec()


    def _run_transformation_from_dialog(self):
        """Read settings from dialog and run the actual transformation."""

        export_blocked = False

        # Track all feature-level geometry fixes in a structured way
        repair_log = {}  # { feature_id : [ "message1", "message2" ] }
        
        # Track validations to reflect in csv report
        validation_rows = []
        # GH-6: ordered set via dict keys (CPython 3.7+) — collects unique NodeIDs
        # as features are processed, feeding the optional Master Data XLSX writer.
        unique_node_ids = {}

        # Validate selected layer
        idx = self.dlg.layerComboBox.currentIndex()
        if idx < 0 or idx >= len(self._polygon_layers):
            QMessageBox.warning(
                self.iface.mainWindow(),
                self.tr("TRACT Geolocation Formatter"),
                self.tr("Please select an input polygon layer."),
            )
            return

        layer = self._polygon_layers[idx]

        if layer.geometryType() not in (
            QgsWkbTypes.PolygonGeometry,
        ):
            QMessageBox.warning(
                self.iface.mainWindow(),
                self.tr("TRACT Geolocation Formatter"),
                self.tr("Selected layer is not a polygon or multipolygon layer."),
            )
            return

        field_names = [f.name() for f in layer.fields()]
        if not field_names:
            QMessageBox.warning(
                self.iface.mainWindow(),
                self.tr("TRACT Geolocation Formatter"),
                self.tr("The selected layer has no attributes."),
            )
            return

        # NodeID options
        node_use_existing = self.dlg.nodeExistingRadio.isChecked()
        node_same = self.dlg.nodeSameRadio.isChecked()
        node_auto = self.dlg.nodeAutoRadio.isChecked()
        node_build = self.dlg.nodeBuildRadio.isChecked()

        # Fixed NodeID value for all polygons
        node_same_value = ""
        if node_same:
            node_same_value = self.dlg.nodeSameLineEdit.text().strip()

        # Optional prefix for auto-generated NodeIDs
        node_prefix = ""
        if node_auto:
            node_prefix = self.dlg.nodePrefixLineEdit.text() or ""

        # Build from expression params
        node_build_params = {}
        if node_build:
            node_build_field1 = self.dlg.nodeBuildField1Combo.currentText()
            if not node_build_field1:
                QMessageBox.warning(
                    self.iface.mainWindow(),
                    self.tr("TRACT Geolocation Formatter"),
                    self.tr("Please select at least Field 1 for the NodeID expression."),
                )
                return
            node_build_params = {
                "prefix": self.dlg.nodeBuildPrefixLineEdit.text().strip(),
                "field1": node_build_field1,
                "field2": self.dlg.nodeBuildField2Combo.currentText() or "",
                "suffix": self.dlg.nodeBuildSuffixLineEdit.text().strip(),
                "separator": self.dlg.nodeBuildSepLineEdit.text() or "_",
            }

        # Must choose one method
        if not node_use_existing and not node_same and not node_auto and not node_build:
            QMessageBox.warning(
                self.iface.mainWindow(),
                self.tr("TRACT Geolocation Formatter"),
                self.tr("Please choose how to create NodeID (existing field, same NodeID for all polygons, or auto-generate)."),
            )
            return

        # If using an existing field, validate field selection
        node_field_name = None
        if node_use_existing:
            node_field_name = self.dlg.nodeFieldCombo.currentText()
            if not node_field_name:
                QMessageBox.warning(
                    self.iface.mainWindow(),
                    self.tr("TRACT Geolocation Formatter"),
                    self.tr("Please select a NodeID field."),
                )
                return

        if node_same and not node_same_value:
            QMessageBox.warning(
                self.iface.mainWindow(),
                self.tr("TRACT Geolocation Formatter"),
                self.tr("Please enter the NodeID value to assign to all polygons."),
            )
            return

        # PlotID options
        plot_none = self.dlg.plotNoneRadio.isChecked()
        plot_existing = self.dlg.plotExistingRadio.isChecked()
        plot_auto = self.dlg.plotAutoRadio.isChecked()
        plot_build = self.dlg.plotBuildRadio.isChecked()

        plot_field_name = None
        plot_prefix = ""

        if plot_existing:
            plot_field_name = self.dlg.plotFieldCombo.currentText()
            if not plot_field_name:
                QMessageBox.warning(
                    self.iface.mainWindow(),
                    self.tr("TRACT Geolocation Formatter"),
                    self.tr("Please select a PlotID field or choose 'No PlotID'."),
                )
                return
        elif plot_auto:
            plot_prefix = self.dlg.plotPrefixLineEdit.text() or ""

        # Build from expression params - PlotID
        plot_build_params = {}
        if plot_build:
            plot_build_field1 = self.dlg.plotBuildField1Combo.currentText()
            if not plot_build_field1:
                QMessageBox.warning(
                    self.iface.mainWindow(),
                    self.tr("TRACT Geolocation Formatter"),
                    self.tr("Please select at least Field 1 for the PlotID expression."),
                )
                return
            plot_build_params = {
                "prefix": self.dlg.plotBuildPrefixLineEdit.text().strip(),
                "field1": plot_build_field1,
                "field2": self.dlg.plotBuildField2Combo.currentText() or "",
                "suffix": self.dlg.plotBuildSuffixLineEdit.text().strip(),
                "separator": self.dlg.plotBuildSepLineEdit.text() or "_",
            }

        # Master Data options (GH-6) — opt-in checkbox + type + country (DEC-11, DEC-12)
        generate_master_data = self.dlg.masterDataCheckBox.isChecked()
        master_data_type = None
        master_data_country = None
        if generate_master_data:
            master_data_type = (
                "farms" if self.dlg.farmsTypeRadio.isChecked() else "farmer_groups"
            )
            if self.dlg.countryCombo.currentIndex() <= 0:
                QMessageBox.warning(
                    self.iface.mainWindow(),
                    self.tr("TRACT Geolocation Formatter"),
                    self.tr("Please select a country for the Master Data file."),
                )
                return
            master_data_country = self.dlg.countryCombo.currentText()

        # Output path
        output_path = self.dlg.outputPathLineEdit.text().strip()
        if not output_path:
            QMessageBox.warning(
                self.iface.mainWindow(),
                self.tr("TRACT Geolocation Formatter"),
                self.tr("Please choose an output GeoJSON path."),
            )
            return

        if not output_path.lower().endswith((".geojson", ".json")):
            output_path += ".geojson"
            self.dlg.outputPathLineEdit.setText(output_path)

        # Check if output file already exists - ask user to confirm overwrite;
        # Commented for now to avoid double checking this after accepting in 'browse' dialog, but can be re-enabled if we want an extra safety check before export
        # if os.path.exists(output_path):
        #     reply = QMessageBox.question(
        #         self.iface.mainWindow(),
        #         self.tr("Replace existing file?"),
        #         self.tr(
        #             "The output file already exists:\n\n{}\n\nDo you want to replace it?"
        #         ).format(output_path),
        #         QMessageBox.Yes | QMessageBox.No,
        #         QMessageBox.No,
        #     )
        #     if reply != QMessageBox.Yes:
        #         return


        self._log(self.tr("Starting TRACT GeoJSON export..."))
        self._log(self.tr("Input layer: {}").format(layer.name()))
        self._log(self.tr("Output file: {}").format(output_path))

        # Prepare CRS transform to EPSG:4326
        target_crs = QgsCoordinateReferenceSystem("EPSG:4326")
        transform_context = QgsProject.instance().transformContext()
        source_crs = layer.crs()
        coord_transform = None

        if not source_crs.isValid():
            QMessageBox.warning(
                self.iface.mainWindow(),
                self.tr("TRACT Geolocation Formatter"),
                self.tr("Input layer has no valid CRS defined."),
            )
            return

        if source_crs != target_crs:
            coord_transform = QgsCoordinateTransform(source_crs, target_crs, transform_context)
            self._log(self.tr("Reprojecting geometries to EPSG:4326..."))
        else:
            self._log(self.tr("Layer already in EPSG:4326."))

        # Transformation to calculate areas: after geometry is already in EPSG:4326, we can transform to an equal-area CRS to calculate areas for minimum area checks
        area_transform = QgsCoordinateTransform(
            target_crs,
            AREA_CRS,
            transform_context
        )

        if layer.crs() != target_crs:
            coord_transform = QgsCoordinateTransform(layer.crs(), target_crs, transform_context)
            self._log(self.tr("Reprojecting geometries to EPSG:4326..."))
        else:
            self._log(self.tr("Layer already in EPSG:4326."))

        # Build excluded fields set (fields mapped to NodeID/PlotID via "Use existing field")
        excluded_fields = set()
        if node_use_existing and node_field_name:
            excluded_fields.add(node_field_name)
        if plot_existing and plot_field_name:
            excluded_fields.add(plot_field_name)

        # Output fields: original layer fields (with exclusion/rename) + TRACT fields
        out_fields, rename_map = self._build_output_fields(layer.fields(), excluded_fields)

        geom_type = layer.wkbType()
        geom_type_2d = QgsWkbTypes.dropZ(geom_type)

        save_options = QgsVectorFileWriter.SaveVectorOptions()
        save_options.driverName = "GeoJSON"
        save_options.fileEncoding = "UTF-8"

        writer = QgsVectorFileWriter.create(
            output_path,
            out_fields,
            geom_type_2d,
            target_crs,
            QgsProject.instance().transformContext(),
            save_options
        )

        if writer.hasError() != QgsVectorFileWriter.NoError:
            QMessageBox.critical(
                self.iface.mainWindow(),
                self.tr("TRACT Geolocation Formatter"),
                self.tr("Error creating output file: {}").format(writer.errorMessage()),
            )
            del writer
            return

        invalid_features = []
        written_count = 0
        total_count = 0
        needs_fix_count = 0
        skipped_count = 0

        small_area_features = []  # list of (fid, area_ha)
        small_area_part_features = []  # list of (fid, part_idx, part_area_ha)
        polygon_hole_features = []  # list of fids
        tract_manual_fix_features = []  # list of (fid, [errors])


        features = list(layer.getFeatures())
        features.sort(key=lambda x: x.id())  # deterministic ordering

        total_features = len(features)

        # Create progress bar in QGIS message bar
        progress_message = self.iface.messageBar().createMessage(
            "TRACT Geolocation Formatter:  Processing features..."
        )
        progress = QProgressBar()
        progress.setMaximum(total_features)
        progress.setValue(0)
        progress.setFormat("%v / %m")
        progress.setAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
        progress_message.layout().addWidget(progress)
        progress_item = self.iface.messageBar().pushWidget(progress_message, Qgis.Info)

        try:
            for i, f in enumerate(features, start=1):
                progress.setValue(i)
                QApplication.processEvents()

                total_count += 1
                feature_status = "READY"
                feature_issues = []
                geom = QgsGeometry(f.geometry())

                if geom.isEmpty():
                    invalid_features.append((f.id(), "Empty geometry"))
                    skipped_count += 1
                    continue

                if geom.isNull():
                    invalid_features.append((f.id(), "Null geometry"))
                    skipped_count += 1
                    continue

                # Moved checking validity to after rounding, because some invalidities are caused by excessive precision and can be fixed by rounding
                # if not geom.isGeosValid():
                #     fixed = geom.makeValid()
                #     if fixed.isEmpty() or not fixed.isGeosValid():
                #         invalid_features.append((f.id(), "Invalid geometry (cannot make valid)"))
                #         continue
                #     geom = fixed

                # --- Z-value removal ---
                if self._has_z_values(geom):
                    if f.id() not in repair_log:
                        repair_log[f.id()] = []
                    repair_log[f.id()].append("Removed Z values")

                    node_id, plot_id = self._get_ids(
                        f,
                        layer,
                        node_use_existing,
                        node_field_name,
                        node_same,
                        node_same_value,
                        plot_existing,
                        plot_field_name,
                    )

                    validation_rows.append({
                        "feature_id": f.id(),
                        "NodeID": node_id,
                        "PlotID": plot_id,
                        "status": "WARNING",
                        "issue_type": "z_values",
                        "message": "Removed Z values"
                    })

                # Reproject to EPSG:4326 first
                if coord_transform is not None:
                    try:
                        geom.transform(coord_transform)
                    except Exception as e:
                        invalid_features.append((f.id(), "Reprojection error: {}".format(e)))
                        skipped_count += 1
                        continue

                # Truncate coordinates once, after reprojection, before checks
                rounded_geom = self._truncate_geometry_coordinates(geom, COORD_DECIMALS)

                if rounded_geom.isEmpty():
                    invalid_features.append((f.id(), "Geometry became empty after coordinate rounding"))
                    skipped_count += 1
                    continue

                if not rounded_geom.equals(geom):
                    if f.id() not in repair_log:
                        repair_log[f.id()] = []
                    repair_log[f.id()].append(f"Rounded coordinates to {COORD_DECIMALS} decimals")

                    node_id, plot_id = self._get_ids(
                        f,
                        layer,
                        node_use_existing,
                        node_field_name,
                        node_same,
                        node_same_value,
                        plot_existing,
                        plot_field_name,
                    )

                    validation_rows.append({
                        "feature_id": f.id(),
                        "NodeID": node_id,
                        "PlotID": plot_id,
                        "status": "WARNING",
                        "issue_type": "coordinate_rounding",
                        "message": f"Rounded coordinates to {COORD_DECIMALS} decimals"
                    })

                geom = rounded_geom

                # Duplicate vertex check after rounding, because rounding can create duplicates
                coords = [(v.x(), v.y()) for v in geom.vertices()]
                has_bad_duplicates = False
                for j in range(len(coords) - 1):
                    if coords[j] == coords[j + 1]:
                        has_bad_duplicates = True
                        break

                if has_bad_duplicates:
                    self._log(f"Fixing consecutive duplicate vertices in feature {f.id()}...")

                    if f.id() not in repair_log:
                        repair_log[f.id()] = []

                    repair_log[f.id()].append("Removed consecutive duplicate vertices")

                    node_id, plot_id = self._get_ids(
                        f,
                        layer,
                        node_use_existing,
                        node_field_name,
                        node_same,
                        node_same_value,
                        plot_existing,
                        plot_field_name,
                    )

                    validation_rows.append({
                        "feature_id": f.id(),
                        "NodeID": node_id,
                        "PlotID": plot_id,
                        "status": "WARNING",
                        "issue_type": "duplicate_vertices",
                        "message": "Removed consecutive duplicate vertices"
                    })

                    geom = self._fix_duplicate_vertices(geom)

                    if geom.isEmpty():
                        invalid_features.append((f.id(), "Empty or invalid geometry after rounding and fixing duplicate vertices"))
                        skipped_count += 1
                        continue

                # 5. NOW check validity, because truncation may have created self-intersections
                if not geom.isGeosValid():
                    if f.id() not in repair_log:
                        repair_log[f.id()] = []

                    repair_log[f.id()].append("Geometry became invalid after truncation; applied makeValid()")

                    node_id, plot_id = self._get_ids(
                        f,
                        layer,
                        node_use_existing,
                        node_field_name,
                        node_same,
                        node_same_value,
                        plot_existing,
                        plot_field_name,
                    )

                    validation_rows.append({
                        "feature_id": f.id(),
                        "NodeID": node_id,
                        "PlotID": plot_id,
                        "status": "WARNING",
                        "issue_type": "invalid_geometry",
                        "message": "Applied makeValid()"
                    })

                    original_invalid_geom = QgsGeometry(geom)


                fixed = geom.makeValid()
                fixed = self._extract_polygonal_geometry(fixed)

                if fixed.isEmpty():
                    # Could not recover a valid polygonal geometry, so keep original geometry
                    # and mark feature for manual fixing
                    feature_status = "NEEDS_FIX"
                    feature_issues.append("Automatic geometry repair failed; manual fix required")

                    node_id, plot_id = self._get_ids(
                        f,
                        layer,
                        node_use_existing,
                        node_field_name,
                        node_same,
                        node_same_value,    
                        plot_existing,
                        plot_field_name,
                    )

                    validation_rows.append({
                        "feature_id": f.id(),
                        "NodeID": node_id,
                        "PlotID": plot_id,
                        "status": "ERROR",
                        "issue_type": "invalid_geometry_unrepaired",
                        "message": "Automatic geometry repair failed; manual fix required"
                    })

                    if f.id() not in repair_log:
                        repair_log[f.id()] = []
                    repair_log[f.id()].append("Automatic repair failed; original geometry kept and marked as NEEDS_FIX")

                    geom = original_invalid_geom

                elif not fixed.isGeosValid():
                    # Repair attempt returned polygonal geometry, but it is still invalid
                    feature_status = "NEEDS_FIX"
                    feature_issues.append("Geometry remains invalid after automatic repair; manual fix required")

                    node_id, plot_id = self._get_ids(
                        f,
                        layer,
                        node_use_existing,
                        node_field_name,
                        node_same,
                        node_same_value,
                        plot_existing,
                        plot_field_name,
                    )

                    validation_rows.append({
                        "feature_id": f.id(),
                        "NodeID": node_id,
                        "PlotID": plot_id,
                        "status": "ERROR",
                        "issue_type": "invalid_geometry_unrepaired",
                        "message": "Geometry remains invalid after automatic repair; manual fix required"
                    })

                    if f.id() not in repair_log:
                        repair_log[f.id()] = []
                    repair_log[f.id()].append("Automatic repair did not fully fix geometry; original geometry retained and marked as NEEDS_FIX")

                    geom = original_invalid_geom

                else:
                    geom = fixed


                # Final TRACT-style geometry checks after truncation / duplicate cleanup / makeValid
                tract_errors = self._get_tract_geometry_errors(geom)

                if tract_errors:
                    feature_status = "NEEDS_FIX"
                    feature_issues.extend(tract_errors)
                    tract_manual_fix_features.append((f.id(), tract_errors))

                    node_id, plot_id = self._get_ids(
                        f,
                        layer,
                        node_use_existing,
                        node_field_name,
                        node_same,
                        node_same_value,
                        plot_existing,
                        plot_field_name,
                    )

                    for err in tract_errors:
                        validation_rows.append({
                            "feature_id": f.id(),
                            "NodeID": node_id,
                            "PlotID": plot_id,
                            "status": "ERROR",
                            "issue_type": "tract_geometry_validation",
                            "message": err
                        })


                # Minimum area check
                try:
                    area_geom = QgsGeometry(geom)
                    area_geom.transform(area_transform)
                    area_m2 = area_geom.area()
                    area_ha = area_m2 / 10000.0
                except Exception as e:
                    invalid_features.append((f.id(), f"Area computation failed: {e}"))
                    skipped_count += 1
                    continue

                if area_ha < MIN_PLOT_AREA_HA:
                    small_area_features.append((f.id(), area_ha))
                    feature_status = "NEEDS_FIX"
                    feature_issues.append(f"Area below minimum ({area_ha:.4f} ha < {MIN_PLOT_AREA_HA} ha)")

                    node_id, plot_id = self._get_ids(
                        f,
                        layer,
                        node_use_existing,
                        node_field_name,
                        node_same,
                        node_same_value,
                        plot_existing,
                        plot_field_name,
                    )

                    validation_rows.append({
                        "feature_id": f.id(),
                        "NodeID": node_id,
                        "PlotID": plot_id,
                        "status": "ERROR",
                        "issue_type": "small_area",
                        "message": f"Area below minimum ({area_ha:.4f} ha < {MIN_PLOT_AREA_HA} ha)"
                    })

                # Per-part minimum area check (multipolygons with 2+ parts only)
                if geom.isMultipart():
                    multipoly = geom.asMultiPolygon()
                    if len(multipoly) > 1:
                        for part_idx, part in enumerate(multipoly, start=1):
                            try:
                                part_geom = QgsGeometry.fromPolygonXY(part)
                                part_area_geom = QgsGeometry(part_geom)
                                part_area_geom.transform(area_transform)
                                part_area_m2 = part_area_geom.area()
                                part_area_ha = part_area_m2 / 10000.0
                            except Exception:
                                continue

                            if part_area_ha < MIN_PLOT_AREA_HA:
                                small_area_part_features.append((f.id(), part_idx, part_area_ha))
                                feature_status = "NEEDS_FIX"
                                feature_issues.append(
                                    f"Polygon part {part_idx} area below minimum "
                                    f"({part_area_ha:.4f} ha < {MIN_PLOT_AREA_HA} ha)"
                                )

                                node_id, plot_id = self._get_ids(
                                    f,
                                    layer,
                                    node_use_existing,
                                    node_field_name,
                                    node_same,
                                    node_same_value,
                                    plot_existing,
                                    plot_field_name,
                                )

                                validation_rows.append({
                                    "feature_id": f.id(),
                                    "NodeID": node_id,
                                    "PlotID": plot_id,
                                    "status": "ERROR",
                                    "issue_type": "small_area_part",
                                    "message": (
                                        f"Polygon part {part_idx} area below minimum "
                                        f"({part_area_ha:.4f} ha < {MIN_PLOT_AREA_HA} ha)"
                                    ),
                                })

                # Polygon holes detection (report only)
                has_holes = False

                if geom.isMultipart():
                    multipoly = geom.asMultiPolygon()
                    for poly in multipoly:
                        if len(poly) > 1:  # exterior ring + one or more interior rings
                            has_holes = True
                            break
                else:
                    poly = geom.asPolygon()
                    if poly and len(poly) > 1:
                        has_holes = True

                if has_holes:
                    polygon_hole_features.append(f.id())
                    feature_status = "NEEDS_FIX"
                    feature_issues.append("Polygon contains interior holes")

                    node_id, plot_id = self._get_ids(
                        f,
                        layer,
                        node_use_existing,
                        node_field_name,
                        node_same,
                        node_same_value,
                        plot_existing,
                        plot_field_name,
                    )

                    validation_rows.append({
                        "feature_id": f.id(),
                        "NodeID": node_id,
                        "PlotID": plot_id,
                        "status": "ERROR",
                        "issue_type": "polygon_holes",
                        "message": "Polygon contains interior holes"
                    })



                if feature_status == "NEEDS_FIX":
                    needs_fix_count += 1

                new_feat = QgsFeature(out_fields)

                # Copy original field values
                for field in layer.fields():
                    name = field.name()
                    if name in excluded_fields:
                        continue
                    source_idx = layer.fields().indexFromName(name)
                    val = f.attributes()[source_idx]
                    output_name = rename_map.get(name, name)
                    new_feat[output_name] = val

                # NodeID
                if node_use_existing:
                    attrs = f.attributes()
                    node_idx = layer.fields().indexFromName(node_field_name)
                    val = attrs[node_idx] if node_idx != -1 else None
                    new_feat["NodeID"] = "" if val is None else str(val)
                elif node_same:
                    new_feat["NodeID"] = node_same_value
                elif node_build:
                    new_feat["NodeID"] = self._build_expression_value(
                        f, layer,
                        node_build_params["prefix"],
                        node_build_params["field1"],
                        node_build_params["field2"],
                        node_build_params["suffix"],
                        node_build_params["separator"],
                    )
                else:
                    new_feat["NodeID"] = f"{node_prefix}{written_count + 1}"

                # GH-6: accumulate unique NodeIDs for the optional Master Data writer.
                # Only runs when the checkbox was checked — small perf optimization.
                if generate_master_data:
                    _node_id_value = new_feat["NodeID"]
                    if _node_id_value:
                        unique_node_ids.setdefault(_node_id_value, None)

                # PlotID
                if plot_none:
                    new_feat["PlotID"] = ""
                elif plot_existing and plot_field_name:
                    attrs = f.attributes()
                    plot_idx = layer.fields().indexFromName(plot_field_name)
                    val = attrs[plot_idx] if plot_idx != -1 else None
                    new_feat["PlotID"] = "" if val is None else str(val)
                elif plot_build:
                    new_feat["PlotID"] = self._build_expression_value(
                        f, layer,
                        plot_build_params["prefix"],
                        plot_build_params["field1"],
                        plot_build_params["field2"],
                        plot_build_params["suffix"],
                        plot_build_params["separator"],
                    )
                elif plot_auto:
                    new_feat["PlotID"] = "{}{}".format(plot_prefix, written_count + 1)
                else:
                    new_feat["PlotID"] = ""

                new_feat["TRACTStatus"] = feature_status
                new_feat["TRACTIssue"] = "; ".join(feature_issues) if feature_issues else ""

                new_feat.setGeometry(geom)

                if not writer.addFeature(new_feat):
                    invalid_features.append((f.id(), "Failed to write feature to output"))
                    skipped_count += 1
                    continue

                written_count += 1

        finally:
            self.iface.messageBar().popWidget(progress_item)

        del writer  # flush

        # Load output layer into QGIS
        layer_name = os.path.basename(output_path)
        output_layer = QgsVectorLayer(output_path, layer_name, "ogr")

        if output_layer.isValid():
            QgsProject.instance().addMapLayer(output_layer)
        else:
            self.iface.messageBar().pushMessage(
                "TRACT Geolocation Formatter",
                "Output file created but could not be loaded into QGIS.",
                level=Qgis.Warning,
                duration=5
            )

        self.iface.messageBar().pushMessage(
            "TRACT Geolocation Formatter",
            f"Finished processing {total_count} features.",
            level=Qgis.Success,
            duration=3
        )

        # # Log small area features
        # if small_area_features:
        #     lines = [
        #         self.tr("Export blocked: polygons below minimum area detected."),
        #         self.tr("Minimum allowed area: {} ha").format(MIN_PLOT_AREA_HA),
        #         self.tr("Number of invalid polygons: {}").format(len(small_area_features)),
        #         "",
        #         self.tr("Examples:")
        #     ]

        #     for fid, area in small_area_features[:10]:
        #         lines.append(f"  FID {fid}: {area:.4f} ha")

        #     if len(small_area_features) > 10:
        #         lines.append(
        #             f"  ... and {len(small_area_features) - 10} more polygons."
        #         )

        #     export_blocked = True

        def _feature_label(fid):
            """
            Helper to build a human-readable feature label, including PlotID if present.
            """
            plot_id = None

            if fid < len(features):
                f = features[fid]
                if plot_existing and plot_field_name:
                    idx = layer.fields().indexFromName(plot_field_name)
                    if idx != -1:
                        val = f.attributes()[idx]
                        if val not in (None, ""):
                            plot_id = str(val)

            if plot_id:
                return f"Feature {fid +1} (PlotID = {plot_id})" # Adding 1 to fid for user-friendly 1-based indexing
            else:
                return f"Feature {fid +1}"


        # BUILD SUMMARY REPORT
        
        # # Count skipped features
        # skipped_invalid_features = (
        #     len(invalid_features)
        #     + len(small_area_features)
        #     + len(polygon_hole_features)
        # )

        summary_lines = [
            self.tr("TRACT GeoJSON export finished."),
            self.tr("Output file: {}").format(output_path),
            self.tr(""),
            self.tr("Total input features: {}").format(total_count),
            self.tr("Successfully written features: {}").format(written_count),
            self.tr("Written features needing manual fix: {}").format(needs_fix_count),
            self.tr("Skipped features: {}").format(skipped_count),
        ]

        if skipped_count > 0:
            summary_lines.append("")
            summary_lines.append(self.tr("WARNING: Some features could not be written to the output file."))
            summary_lines.append(self.tr("The output file contains fewer geolocations than the input file."))
            summary_lines.append(self.tr("Please review the skipped features before using the output."))

        if needs_fix_count > 0:
            summary_lines.append("")
            summary_lines.append(self.tr("WARNING: Some written features still require manual fixing before upload to TRACT."))
            summary_lines.append(self.tr("These features are included in the output file with TRACTStatus = NEEDS_FIX."))
            summary_lines.append("")


        if invalid_features:
            summary_lines.append("")
            summary_lines.append(self.tr("Skipped features:"))
            for fid, reason in invalid_features[:500]:
                summary_lines.append(f"  - {_feature_label(fid)}: {reason}")

    


        # --- Blocking validation errors (grouped) ---
        # --- Written features requiring manual fix (grouped) ---
        if small_area_features or small_area_part_features or polygon_hole_features or tract_manual_fix_features:
            summary_lines.append("")
            summary_lines.append(self.tr("Written features requiring manual fix:"))

            if small_area_features:
                summary_lines.append(
                    self.tr("Polygons below minimum area ({} ha):").format(MIN_PLOT_AREA_HA)
                )
                for fid, area in small_area_features[:500]:
                    summary_lines.append(
                        f"  - {_feature_label(fid)}: {area:.4f} ha"
                    )

                if len(small_area_features) > 500:
                    summary_lines.append(
                        f"  ... and {len(small_area_features) - 500} more polygons."
                    )

            if small_area_part_features:
                summary_lines.append("")
                summary_lines.append(
                    self.tr("Polygon parts below minimum area ({} ha):").format(MIN_PLOT_AREA_HA)
                )
                for fid, part_idx, area in small_area_part_features[:500]:
                    summary_lines.append(
                        f"  - {_feature_label(fid)}, part {part_idx}: {area:.4f} ha"
                    )

                if len(small_area_part_features) > 500:
                    summary_lines.append(
                        f"  ... and {len(small_area_part_features) - 500} more polygon parts."
                    )

            if polygon_hole_features:
                summary_lines.append("")
                summary_lines.append(
                    self.tr("Polygons with interior holes detected:")
                )

                for fid in polygon_hole_features[:500]:
                    summary_lines.append(
                        f"  - {_feature_label(fid)}"
                    )

                if len(polygon_hole_features) > 500:
                    summary_lines.append(
                        f"  ... and {len(polygon_hole_features) - 500} more polygons."
                    )


            if tract_manual_fix_features:
                summary_lines.append("")
                summary_lines.append(
                    self.tr("TRACT-specific geometry validation issues:")
                )

                for fid, errors in tract_manual_fix_features[:500]:
                    summary_lines.append(
                        f"  - {_feature_label(fid)}: {'; '.join(errors)}"
                    )

                if len(tract_manual_fix_features) > 500:
                    summary_lines.append(
                        f"  ... and {len(tract_manual_fix_features) - 500} more polygons."
                    )



        if repair_log:

            summary_lines.append(
            self.tr("Features with geometry repairs applied: {}").format(len(repair_log))
            )

            summary_lines.append("")
            summary_lines.append(self.tr("Geometry repair details:"))

            max_display = 100
            display_ids = list(repair_log.keys())[:max_display]

            for fid in display_ids:
                messages = repair_log[fid]
                for msg in messages:
                    summary_lines.append(f"  - {_feature_label(fid)}: {msg}")

            if len(repair_log) > max_display:
                summary_lines.append(
                    f"  ... and {len(repair_log) - max_display} more features with repairs."
                )


        summary_text = "\n".join(summary_lines)
        self._log(summary_text)

        # Write validation report CSV if there are any validation rows
        report_path = None
        if validation_rows:
            report_path = os.path.splitext(output_path)[0] + "_validation_report.csv"

            import csv
            with open(report_path, "w", newline="", encoding="utf-8") as f:
                writer = csv.DictWriter(
                    f,
                    fieldnames=[
                        "feature_id",
                        "NodeID",
                        "PlotID",
                        "status",
                        "issue_type",
                        "message",
                    ],
                )
                writer.writeheader()
                for row in validation_rows:
                    writer.writerow(row)

        if report_path:
            summary_lines.append(self.tr(""))
            summary_lines.append(self.tr("Validation report written to: {}").format(report_path))

        # GH-6: optional Master Data XLSX write — runs after GeoJSON + CSV report
        # are produced. Failure here surfaces as a warning but does NOT mark the
        # whole export as failed (the primary outputs are already on disk).
        if generate_master_data and unique_node_ids:
            template_filename = (
                "farms_master_data_template.xlsx"
                if master_data_type == "farms"
                else "farmer_group_master_data_template.xlsx"
            )
            template_path = os.path.join(
                self.plugin_dir, "templates", template_filename
            )
            master_data_output = _master_data_output_path(output_path, master_data_type)
            try:
                _write_master_data_xlsx(
                    template_path,
                    master_data_output,
                    master_data_type,
                    master_data_country,
                    list(unique_node_ids.keys()),
                )
                self._log(
                    self.tr("Master Data file written: {}").format(master_data_output)
                )
                summary_lines.append(self.tr(""))
                summary_lines.append(
                    self.tr("Master Data file written to: {}").format(master_data_output)
                )
            except Exception as e:
                self._log(self.tr("Master Data write failed: {}").format(e))
                QMessageBox.warning(
                    self.iface.mainWindow(),
                    self.tr("TRACT Geolocation Formatter"),
                    self.tr("The Master Data file could not be written: {}").format(e),
                )
        elif generate_master_data and not unique_node_ids:
            # DEC-13 defensive case — should not occur in practice (NodeID is compulsory).
            self._log("No unique NodeIDs to write; master data file not produced.")

        # Rebuilds summary text
        summary_text = "\n".join(summary_lines)
        self._log(summary_text)

        self._show_report_dialog(summary_text)
